language: node_js

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - '8'
  - '10'
  - '11'
  - '12'
script:
  - yarn build # make sure build works fine
  - yarn test

cache:
  yarn: true
  directories:
    - node_modules